credentials:
  usernames:
    admin:
      name: Admin User
      email: admin@example.com
      password: "$2b$12$yWmP5sL2wKJe3qT1aBv.OepNGCRXjtwFtGfbFpfu9uMfU67XkmXmm"  # Hashed "admin123"

cookie:
  expiry_days: 30
  key: "a_random_secret_key"
  name: "expense_splitter_auth"

preauthorized:
  emails:
    - admin@example.com
